version: '3.1'

services:
  postgres:
    image: postgres:12.3
    # restart: always
    ports:
        - 5432:5432
    # volumes:
    #     - ./data/db:/data/db
    env_file:
        - config/test.env
    # environment:
    #   POSTGRES_PASSWORD: password_placeholder
