version: '3.1'

services:
  mongo:
    image: mongo:4.2.7
    restart: always
    ports:
        - 27017:27017
    # volumes:
    #     - ./data/db:/data/db
    env_file:
        - config/test.env
    # environment:
    #     MONGO_INITDB_ROOT_USERNAME: username_placeholder
    #     MONGO_INITDB_ROOT_PASSWORD: password_placeholader