version: '3.1'

services:
  mysql:
    image: mysql:8.0.20
    # restart: always
    ports:
        - 3306:3306
    # volumes:
    #     - ./data/db:/data/db
    env_file:
        - config/test.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: password_placeholder